# This is a sample config file that points to a solr server for each environment
development:
  url: http://127.0.0.1:8983/solr/hydra-development
dcdevhyrax:
  url: http://127.0.0.1:8983/solr/hydra-development
digcollhyrax01:
  url: http://digcoll-solr01.tcd.ie:8983/solr/tcd-hyrax
digcollhyrax02:
  url: http://digcoll-solr02.tcd.ie:8983/solr/tcd-hyrax
test:
  url: <%= ENV['SOLR_TEST_URL'] || ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_TEST_PORT', 8985)}/solr/hydra-test" %>
production:
  url: http://your.production.server:8080/bl_solr/core0
